/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fragments;

import DataModel.DataSummaryCard;

/**
 *
 * @author kimel
 */
public class FragmentCardSummary extends javax.swing.JPanel {

    /**
     * Creates new form FragmentCardSummary
     */
    public FragmentCardSummary() {
        initComponents();
        setOpaque(false);
    }

    public void setData(DataSummaryCard data){
        LBSummaryIcon.setIcon(data.getIcon());
        LBSummaryValue.setText(data.getValue());
        LBSummaryTitle.setText(data.getCategory());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sharpCorner1 = new SwingClass.SharpCorner();
        sharpCorner2 = new SwingClass.SharpCorner();
        LBSummaryValue = new javax.swing.JLabel();
        LBSummaryIcon = new javax.swing.JLabel();
        LBSummaryTitle = new javax.swing.JLabel();

        sharpCorner2.setBackground(new java.awt.Color(0, 82, 155));

        javax.swing.GroupLayout sharpCorner2Layout = new javax.swing.GroupLayout(sharpCorner2);
        sharpCorner2.setLayout(sharpCorner2Layout);
        sharpCorner2Layout.setHorizontalGroup(
            sharpCorner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        sharpCorner2Layout.setVerticalGroup(
            sharpCorner2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        LBSummaryValue.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        LBSummaryValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBSummaryValue.setText("0");

        LBSummaryIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        LBSummaryTitle.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LBSummaryTitle.setForeground(new java.awt.Color(11, 46, 70));
        LBSummaryTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LBSummaryTitle.setText("Active Users");

        javax.swing.GroupLayout sharpCorner1Layout = new javax.swing.GroupLayout(sharpCorner1);
        sharpCorner1.setLayout(sharpCorner1Layout);
        sharpCorner1Layout.setHorizontalGroup(
            sharpCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharpCorner2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sharpCorner1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(sharpCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(LBSummaryTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(LBSummaryValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LBSummaryIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        sharpCorner1Layout.setVerticalGroup(
            sharpCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sharpCorner1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(sharpCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(sharpCorner1Layout.createSequentialGroup()
                        .addComponent(LBSummaryValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LBSummaryTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addComponent(LBSummaryIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(8, 8, 8)
                .addComponent(sharpCorner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sharpCorner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sharpCorner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LBSummaryIcon;
    private javax.swing.JLabel LBSummaryTitle;
    private javax.swing.JLabel LBSummaryValue;
    private SwingClass.SharpCorner sharpCorner1;
    private SwingClass.SharpCorner sharpCorner2;
    // End of variables declaration//GEN-END:variables
}
