/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Fragments;

import DataModel.DataRankSummary;
import DataModel.DataSummaryCard;
import futuristicbio.biometrics.CrudOperations;
import java.util.ArrayList;
import javax.swing.ImageIcon;

/**
 *
 * @author kimel
 */
public class FragmentDashboard extends javax.swing.JPanel {

    private CrudOperations co;
    
    public FragmentDashboard() {
        initComponents();
        co = new CrudOperations();
        ArrayList<String> values = co.getSummary();
        ArrayList<String> ranks = co.getRankSummary();
        ArrayList<String> states = co.getStateSummary();
        
        
        card1.setData(new DataSummaryCard("Total Number of Enrollees", values.get(2), new ImageIcon(getClass().getResource("/resources/UICons/20.png"))));
        card2.setData(new DataSummaryCard("Total Number of Male Enrollees", values.get(0), new ImageIcon(getClass().getResource("/resources/UICons/21.png"))));
        card3.setData(new DataSummaryCard("Total Number of Female Enrollees", values.get(1), new ImageIcon(getClass().getResource("/resources/UICons/23.png"))));
        card4.setData(new DataSummaryCard("Total Number of Information Updates", values.get(3), new ImageIcon(getClass().getResource("/resources/UICons/sale-report.png"))));
        card5.setData(new DataSummaryCard("Active System Users", values.get(4), new ImageIcon(getClass().getResource("/resources/UICons/22.png"))));
        fragmentRankSummary1.setData(new DataRankSummary("Total Number of Enrollees per Rank", ranks, new ImageIcon(getClass().getResource("/resources/UICons/24.png"))));
        fragmentTotalSummary1.setData(new DataRankSummary("Total Number of Enrollees per State", states, new ImageIcon(getClass().getResource("/resources/UICons/18.png"))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundCorner1 = new SwingClass.RoundCorner();
        jScrollPane2 = new javax.swing.JScrollPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        card1 = new Fragments.FragmentCardSummary();
        card2 = new Fragments.FragmentCardSummary();
        card3 = new Fragments.FragmentCardSummary();
        card4 = new Fragments.FragmentCardSummary();
        card5 = new Fragments.FragmentCardSummary();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        fragmentTotalSummary1 = new Fragments.FragmentTotalSummary();
        fragmentRankSummary1 = new Fragments.FragmentRankSummary();

        jLayeredPane1.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane1.add(card1);
        jLayeredPane1.add(card2);
        jLayeredPane1.add(card3);
        jLayeredPane1.add(card4);
        jLayeredPane1.add(card5);

        jScrollPane2.setViewportView(jLayeredPane1);

        jLayeredPane2.setLayout(new java.awt.GridLayout(1, 0, 10, 0));
        jLayeredPane2.add(fragmentTotalSummary1);
        jLayeredPane2.add(fragmentRankSummary1);

        jScrollPane3.setViewportView(jLayeredPane2);

        javax.swing.GroupLayout roundCorner1Layout = new javax.swing.GroupLayout(roundCorner1);
        roundCorner1.setLayout(roundCorner1Layout);
        roundCorner1Layout.setHorizontalGroup(
            roundCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1257, Short.MAX_VALUE)
        );
        roundCorner1Layout.setVerticalGroup(
            roundCorner1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundCorner1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 401, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundCorner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(roundCorner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Fragments.FragmentCardSummary card1;
    private Fragments.FragmentCardSummary card2;
    private Fragments.FragmentCardSummary card3;
    private Fragments.FragmentCardSummary card4;
    private Fragments.FragmentCardSummary card5;
    private Fragments.FragmentRankSummary fragmentRankSummary1;
    private Fragments.FragmentTotalSummary fragmentTotalSummary1;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private SwingClass.RoundCorner roundCorner1;
    // End of variables declaration//GEN-END:variables
}
